theme: jekyll-theme-kernel

title: Kernel Theme
logo: /images/logo.png
description: Kernel is a simple static Jekyll theme inspired by kernel.org.
author: Your Name Goes Here

defaults:
        -
                scope:
                        path: ""
                        type: "pages"
                values:
                        layout: "default"
        -
                scope:
                        path: ""
                        type: "posts"
                values:
                        layout: "post"
